/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 HeatWithFire.glb 
*/
"use client"
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function HeatWithFire(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/HeatWithFire.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions["colorChange"].reset().fadeIn(0.5).play();
    setTimeout(() => {
      if (actions["colorChange"])
        actions["colorChange"].reset().fadeIn(0.5).play().paused = true;
    }, 4000);
  }, [])

  console.log(animations)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[-0.383, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="357e8906e1ed4020b649e447185dae7cfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="Headphone_stand_v2" rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
                <group name="Body1" scale={10}>
                  <mesh name="Body1_Carbon_Fiber_-_Twill_0" geometry={nodes['Body1_Carbon_Fiber_-_Twill_0'].geometry} material={materials['Carbon_Fiber_-_Twill']} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" position={[-0.037, 0.178, 0.127]} rotation={[-Math.PI / 2, 0, 1.646]} scale={12.114}>
          <group name="Torch_LPfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode001">
              <group name="group1" position={[0, 0.498, 0.17]} scale={0.496}>
                <group name="flame" position={[0.272, -5.057, 4.368]} rotation={[-1.361, -0.091, -0.093]}>
                  <mesh name="flame_Flame_mat_0" geometry={nodes.flame_Flame_mat_0.geometry} material={materials['Flame_mat.002']} position={[0.846, 0.286, 4.784]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh name="ContainerParaffinHolder_low" geometry={nodes.ContainerParaffinHolder_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ContainerMainScrew_low" geometry={nodes.ContainerMainScrew_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ContainerOpenerMain_low" geometry={nodes.ContainerOpenerMain_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ContainerOpenerTwist_low" geometry={nodes.ContainerOpenerTwist_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ContainerParaffinDeliveryPipe_low" geometry={nodes.ContainerParaffinDeliveryPipe_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunScrewT_low" geometry={nodes.GunScrewT_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ScrewGunRectangle_low" geometry={nodes.ScrewGunRectangle_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunMetalSupport_low" geometry={nodes.GunMetalSupport_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunScrewCylinder_low" geometry={nodes.GunScrewCylinder_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunMainFrameSupport_low" geometry={nodes.GunMainFrameSupport_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunMainFrame_low" geometry={nodes.GunMainFrame_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunScrewSupport_low" geometry={nodes.GunScrewSupport_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="Hanger_low" geometry={nodes.Hanger_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ArmHandle_low" geometry={nodes.ArmHandle_low.geometry} material={materials['Material.004']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ArmHandleCylinder_low" geometry={nodes.ArmHandleCylinder_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ContainerMainScrew_low1" geometry={nodes.ContainerMainScrew_low1.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ContainerMainScrew_low2" geometry={nodes.ContainerMainScrew_low2.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="ContainerMainScrew_low3" geometry={nodes.ContainerMainScrew_low3.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunHoleTriangle1_low5" geometry={nodes.GunHoleTriangle1_low5.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunHoleTriangle1_low2" geometry={nodes.GunHoleTriangle1_low2.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunHoleTriangle1_low3" geometry={nodes.GunHoleTriangle1_low3.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunHolledPart_low" geometry={nodes.GunHolledPart_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunHoleTriangle1_low1" geometry={nodes.GunHoleTriangle1_low1.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunHoleTriangle1_low4" geometry={nodes.GunHoleTriangle1_low4.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="GunHoleTriangle1_low" geometry={nodes.GunHoleTriangle1_low.geometry} material={materials['lambert12.003']} position={[0.416, 0.132, 0.044]} rotation={[Math.PI / 2, 0, -1.646]} scale={0.181} />
        <mesh name="white_rod" geometry={nodes.white_rod.geometry} material={materials['Material.006']} position={[-0.408, 0.296, 0.066]} scale={[0.275, 0.008, 0.023]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Carbon_Fiber_-_Twill']} position={[-0.38, 0.31, 0.069]} scale={[0.028, 0.01, 0.027]} />
        <mesh name="red_rod" geometry={nodes.red_rod.geometry} material={materials['Material.002']} position={[-0.133, 0.293, 0.07]} scale={[0.26, 0.007, 0.022]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/HeatWithFire.glb')
