/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"
import React, { useMemo, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useControls } from 'leva'


export default function TempModel(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/solar-panel/model.gltf')
    // leva start

    const options = useMemo(() => {
        return {
            Position: { value: 10, min: 5, max: 15, step: .01 },
            Weight1: { value: 100, min: 100, max: 800, step: 50 },
            Weight2: { value: 100, min: 100, max: 800, step: 50 },
        }
    }, [])

    const Handler = useControls('Readings', options)

    // leva end
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[0, -0.29, 0,]} rotation={[0, Math.PI / 2, 0,]} />
            <group position={[0.18, -0.29, 0,]} rotation={[Math.PI / 6, 0, 0,]} >
                <mesh geometry={nodes.Cube.geometry} material={materials.SolarCell} />
                <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
                <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
            </group>

        </group>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/solar-panel/model.gltf')

